#!usr/bin/bash | sh

echo "! - Pulling from main"
// git pull origin main
echo "✔ - Done update remote"

echo "! - Testing Build Bundle"
pnpm run build
echo "✔ - Done Running Build"

echo "✔ - Done Running Pre-Push\n"
